### ISSUE TITLE
trojan 

### ISSUE THREAD

**Issue by anonym24** [coldscientist/AutoIt-FO2-Splitscreen#1]
![image](https://user-images.githubusercontent.com/8851301/66863320-6c73ab80-ef9b-11e9-86e3-d83d2b6f9959.png)

**Comment by coldscientist** [comment]
It shouldn't be happening. Maybe it's showing to you because it uses DLLCall (System calls) to change the behavior of FlatOut2.exe process (resize it).
What if I do not feel safe with making AV exceptions?
This project is open source so you can download and review the source code if you want and compile it yourself. This way you know exactly what is running on your computer.
